steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/LetsCloud/mws']
  id: 'CLONE'
  
- name: 'maven:3.6.2-jdk-8-slim'
  args: ['clean']
  dir: 'mws'
  id: 'CLEAN'
  waitFor: ['CLONE']
  entrypoint: 'mvn'
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'

- name: 'maven:3.6.2-jdk-8-slim'
  args: ['-P', 'prod', 'install']
  dir: 'mws'
  id: 'INSTALL'
  waitFor: ['CLEAN']
  entrypoint: 'mvn'
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'

- name: 'maven:3.6.2-jdk-8-slim'
  args: ['package']
  dir: 'mws/mws-server'
  id: 'PACKAGE'
  waitFor: ['INSTALL']
  entrypoint: 'mvn'
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'
  
- id: 'LS'
  waitFor: ['PACKAGE']
  name: 'ubuntu'
  args: ['ls', 'mws/mws-server/target/mws-server-0.0.1-SNAPSHOT/WEB-INF/lib']
  
- id: 'SDK'
  waitFor: ['PACKAGE']
  name: 'google/cloud-sdk:latest'
  args: ['pull', '/workspace/google-cloud-sdk']

# - id: 'MKDIR'
#   waitFor: ['PACKAGE']
#   name: 'ubuntu'
#   args: ['mkdir', 'deploy-build']

# - id: 'COPY XML'
#   waitFor: ['MKDIR']
#   name: 'ubuntu'
#   args: ['cp', 'mws/mws-server/src/main/webapp/WEB-INF/appengine-web.xml', '/workspace/deploy-build/']
  
# - id: 'COPY WAR'
#   waitFor: ['COPY XML']
#   name: 'ubuntu'
#   args: ['cp', 'mws/mws-server/target/mws-server-0.0.1-SNAPSHOT.war', '/workspace/deploy-build/']

# - id: 'DEPLOY'
#   waitFor: ['PACKAGE']
#   name: 'gcr.io/cloud-builders/gcloud'
#   args: ['app', 'deploy', 'mws/mws-server/target/mws-server-0.0.1-SNAPSHOT']


# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['components', 'install', 'app-engine-java']
#   id: 'F'
#   waitFor: ['E']

- name: 'maven:3.6.2-jdk-8-slim'
  args: ['com.google.cloud.tools:appengine-maven-plugin:deploy', 'DcloudSdkHome=/workspace/google-cloud-sdk']
  dir: 'mws/mws-server'
  id: 'MVN_DEPLOY'
  waitFor: ['SDK']
  entrypoint: 'mvn'
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'
  