steps:
- id: 'CLONE'
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/LetsCloud/mws']
  
- id: 'CLEAN'
  waitFor: ['CLONE']
  name: 'maven:3.6.3-jdk-8'
  entrypoint: 'mvn'
  args: ['clean']
  dir: 'mws'  
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'

- id: 'INSTALL'
  waitFor: ['CLEAN']
  name: 'maven:3.6.3-jdk-8'
  entrypoint: 'mvn'
  args: ['-P', 'prod', 'install']
  dir: 'mws'  
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'
  
- id: 'LS'
  waitFor: ['INSTALL']
  name: 'ubuntu'
  args: ['ls', 'mws/mws-server/target/mws-server-0.0.1-SNAPSHOT/WEB-INF/lib']

# - id: 'PACKAGE'
#   waitFor: ['LS']
#   name: 'maven:3.6.3-jdk-8'
#   entrypoint: 'mvn'
#   args: ['package']
#   dir: 'mws/mws-server'  
#   volumes:
#   - name: 'mavenrepo'
#     path: '/root/.m2'

# - id: 'DEPLOY'
#   waitFor: ['PACKAGE']
#   name: 'gcr.io/cloud-builders/gcloud'
#   args: ['app', 'deploy']
#   dir: 'mws/mws-server'  

#   args: ['app', 'deploy', 'mws/mws-server/target/mws-server-0.0.1-SNAPSHOT']

# - id: 'PACKAGEDEPLOY'
#   waitFor: ['LS']
#   name: 'maven:3.6.3-jdk-8'
#   entrypoint: 'mvn'
#   args: ["-D", "skipTests", "package", "appengine:deploy"]
#   dir: 'mws/mws-server'  
#   volumes:
#   - name: 'mavenrepo'
#     path: '/root/.m2'

- id: 'PACKAGEDEPLOY2'
  waitFor: ['LS']
  name: "gcr.io/cloud-builders/mvn"
  args: ["-D", "skipTests", "package", "appengine:deploy"]
  dir: 'mws/mws-server'  
