steps:
- id: 'CLONE'
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/LetsCloud/mws']
  
- id: 'CLEAN'
  waitFor: ['CLONE']
  name: 'maven:3.6.3-jdk-8'
  entrypoint: 'mvn'
  args: ['clean']
  dir: 'mws'  
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'

- id: 'INSTALL'
  waitFor: ['CLEAN']
  name: 'maven:3.6.3-jdk-8'
  entrypoint: 'mvn'
  args: ['-P', 'prod', 'install']
  dir: 'mws'  
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'

- id: 'PACKAGE'
  waitFor: ['INSTALL']
  name: 'maven:3.6.3-jdk-8'
  entrypoint: 'mvn'
  args: ['package']
  dir: 'mws/mws-server'  
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'
  
- id: 'LS'
  waitFor: ['PACKAGE']
  name: 'ubuntu'
  args: ['ls', 'mws/mws-server/target/mws-server-0.0.1-SNAPSHOT/WEB-INF/lib']
  
#- id: 'SDK'
#  waitFor: ['LS']
#  name: 'google/cloud-sdk:latest'
#  args: ['pull', '/workspace/google-cloud-sdk']

# - id: 'MKDIR'
#   waitFor: ['PACKAGE']
#   name: 'ubuntu'
#   args: ['mkdir', 'deploy-build']

# - id: 'COPY XML'
#   waitFor: ['MKDIR']
#   name: 'ubuntu'
#   args: ['cp', 'mws/mws-server/src/main/webapp/WEB-INF/appengine-web.xml', '/workspace/deploy-build/']
  
# - id: 'COPY WAR'
#   waitFor: ['COPY XML']
#   name: 'ubuntu'
#   args: ['cp', 'mws/mws-server/target/mws-server-0.0.1-SNAPSHOT.war', '/workspace/deploy-build/']

- id: 'DEPLOY'
  waitFor: ['LS']
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'mws/mws-server/target/mws-server-0.0.1-SNAPSHOT']


# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['components', 'install', 'app-engine-java']
#   id: 'F'
#   waitFor: ['E']



#- name: 'maven:3.6.2-jdk-8-slim'
#  args: ['com.google.cloud.tools:appengine-maven-plugin:deploy', 'DcloudSdkHome=/workspace/google-cloud-sdk']
#  dir: 'mws/mws-server'
#  id: 'MVN_DEPLOY'
#  waitFor: ['SDK']
#  entrypoint: 'mvn'
#  volumes:
#  - name: 'mavenrepo'
#    path: '/root/.m2'
  