steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/LetsCloud/mws']
  id: 'B'
  
- name: 'maven:3.6.2-jdk-8-slim'
  args: ['clean']
  dir: 'mws'
  id: 'C'
  waitFor: ['B']
  entrypoint: 'mvn'
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'

- name: 'maven:3.6.2-jdk-8-slim'
  args: ['-P', 'prod', 'install']
  dir: 'mws'
  id: 'D'
  waitFor: ['C']
  entrypoint: 'mvn'
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'

- name: 'maven:3.6.2-jdk-8-slim'
  args: ['package']
  dir: 'mws/mws-server'
  id: 'E'
  waitFor: ['D']
  entrypoint: 'mvn'
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['components', 'install', 'app-engine-java']
  id: 'F'
  waitFor: ['E']

- name: 'maven:3.6.2-jdk-8-slim'
  args: ['appengine:deploy']
  dir: 'mws/mws-server'
  id: 'G'
  waitFor: ['F']
  entrypoint: 'mvn'
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'
  