steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/LetsCloud/mws']
  id: 'B'
- name: 'maven:3.6.2-jdk-8-slim'
  args: ['clean']
  dir: 'mws'
  id: 'C'
  waitFor: ['B']
  entrypoint: 'mvn'
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'

- name: 'maven:3.6.2-jdk-8-slim'
  args: ['-P', 'prod', 'install']
  dir: 'mws'
  id: 'D'
  waitFor: ['C']
  entrypoint: 'mvn'
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'

- name: 'maven:3.6.2-jdk-8-slim'
  args: ['-pl', 'mws-server', 'package']
  dir: 'mws'
  id: 'E'
  waitFor: ['D']
  entrypoint: 'mvn'
  volumes:
  - name: 'mavenrepo'
    path: '/root/.m2'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: 'mws/mws-server/target/mws-server-0.0.1-SNAPSHOT'
  id: 'G'
  waitFor: ['E']
