/**
 * 
 */
package io.crs.mws.shared.exception.cnst;

/**
 * @author robi
 *
 */
public enum ErrorMessageCode {
	APPUSER_EMAIL_ALREADY_EXISTS, 
	APPUSER_CODE_ALREADY_EXISTS, 
	
	CONTRACTTYPE_CODE_ALREADY_EXISTS,
	CONTRACTTYPE_IS_USED_BY_CONTRACT,

	QOUTATIONSTATUS_CODE_ALREADY_EXISTS,
	QOUTATIONSTATUS_IS_USED_BY_QOUTATION,
	
	QUOTATION_CODE_ALREADY_EXISTS,
	
	CONTRACT_CODE_ALREADY_EXISTS, 
	
	USERGROUP_NAME_ALREADY_EXISTS,
	
	PROFILEGROUP_CODE_ALREADY_EXISTS, 
	
	MARKETGROUP_CODE_ALREADY_EXISTS, 
	
	PRODUCTTYPE_CODE_ALREADY_EXISTS,
	PRODUCTTYPE_IS_USED_BY_CONTRACT,
	
	ROOMTYPECODE_CODE_ALREADY_EXISTS,
	ROOMCODE_CODE_ALREADY_EXISTS, 
	
	TASKGROUP_CODE_ALREADY_EXISTS, 
	TASKGROUP_ID_USED_BY_TASKTODO, 
	TASKGROUP_ID_USED_BY_TASKTYPE,
	
	TASKTODO_DESCRIPTION_ALREADY_EXISTS,
	
	TASKTYPE_CODE_ALREADY_EXISTS, 
	TASKTYPE_ID_USED_BY_TASK,
	
	OOO_ROOM_OVERLAP
	;
}
